spring.application.name=sortout-job-backend
#Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sortout_jobs_db
spring.datasource.username=sortout
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=your-super-secret-key-should-be-at-least-256-bits-long-for-security
jwt.expiration=86400000

# Refresh Token (7 days in milliseconds)
jwt.refresh-expiration=604800000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=1013699273832-mnf70013l8qvef0p4n5vtitugvn63vv2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
app.oauth2.redirectUri=http://localhost:3000/oauth2/redirect